# Runs the helper prelude of HorizonMW.js under the same Jint engine Nucleus uses,
# against a throwaway sandbox, and asserts the byte-level and text-level behaviour
# that the handler depends on. Touches nothing outside the sandbox.

$ErrorActionPreference = 'Stop'

$repo   = Split-Path -Parent $PSScriptRoot
$jint   = 'C:\NucleusCoop\Jint.dll'
$sandbox = Join-Path $env:TEMP ('hmw-dryrun-' + [Guid]::NewGuid().ToString('N').Substring(0, 8))

Add-Type -Path $jint

# Take only the helper prelude, i.e. everything before the Game definition.
$src    = [IO.File]::ReadAllText((Join-Path $repo 'HorizonMW.js'))
$marker = '// Game definition'
$cut    = $src.IndexOf($marker)
if ($cut -lt 0) { throw "marker '$marker' not found in HorizonMW.js" }
$prelude = $src.Substring(0, $cut)

New-Item -ItemType Directory -Force -Path (Join-Path $sandbox 'src\user'), (Join-Path $sandbox 'inst'), (Join-Path $sandbox 'appdata') | Out-Null

# A source install to seed from: config has a name line, no favourites.json.
$srcP2 = Join-Path $sandbox 'src'
@(
    '// generated by Call of Duty: MWR - do not modify',
    'seta cg_drawFPS "0"',
    'seta name "gargr"',
    'seta com_maxfps "0"',
    # The real render dvars, verbatim from the install, so the viewport test runs
    # against the exact strings and prefix collisions the handler will meet.
    'seta r_aspectRatio "auto"',
    'seta r_renderResolutionNative "0"',
    'seta r_renderResolution "3.6864"',
    'seta vid_xpos "-1"',
    'seta vid_ypos "-1"',
    'seta r_fullscreen "1"',
    'seta r_fullscreenWindow "1"',
    'seta r_mode "2560x1440"'
) -join "`r`n" | Set-Content -LiteralPath (Join-Path $srcP2 'config_mp.cfg') -Encoding Ascii -NoNewline
'{}' | Set-Content -LiteralPath (Join-Path $srcP2 'history.json') -Encoding Ascii -NoNewline
'cdta' | Set-Content -LiteralPath (Join-Path $srcP2 'user\hmwcdta') -Encoding Ascii -NoNewline

# A pre-existing identity to be backed up and restored.
$appdata = Join-Path $sandbox 'appdata'
'REAL-GUID' | Set-Content -LiteralPath (Join-Path $appdata 'hwgd.pf') -Encoding Ascii -NoNewline
'REAL-KEY'  | Set-Content -LiteralPath (Join-Path $appdata 'hmw-key') -Encoding Ascii -NoNewline

$engine = New-Object Jint.Engine ([Action[Jint.Options]] { param($o) [void]$o.AllowClr() })
[void]$engine.Execute($prelude)

# hmwLog swallows its own errors, so prove it actually writes. Jint cannot call
# System.DateTime.Now.ToString(), which once made every log write a silent no-op.
$logPath = Join-Path $env:TEMP 'HorizonMWHandler.log'
$logBefore = if (Test-Path -LiteralPath $logPath) { (Get-Item -LiteralPath $logPath).Length } else { 0 }
$logMarker = 'dryrun-marker-' + [Guid]::NewGuid().ToString('N').Substring(0, 8)
[void]$engine.Execute("hmwLog(" + (ConvertTo-Json $logMarker) + ");")

# Point the identity helpers at the sandbox instead of the real %LOCALAPPDATA%.
[void]$engine.Execute("hmwRealAppData = function () { return " + (ConvertTo-Json $appdata) + "; };")

$jsSandbox = ConvertTo-Json $sandbox
[void]$engine.Execute(@"
var SB      = $jsSandbox;
var srcP2   = SB + '\\src';
var inst    = SB + '\\inst';
var players2 = inst + '\\players2';
var users    = players2 + '\\user';

hmwEnsureDir(players2);
hmwEnsureDir(users);

hmwSeedFile(srcP2 + '\\config_mp.cfg', players2 + '\\config_mp.cfg');
hmwSeedOrCreate(srcP2 + '\\favourites.json', players2 + '\\favourites.json', '[]');
hmwSeedOrCreate(srcP2 + '\\history.json',    players2 + '\\history.json',    '[]');
hmwSeedOrCreate(srcP2 + '\\user\\hmwcdta',   users + '\\hmwcdta', '');
hmwSeedOrCreate(srcP2 + '\\user\\hmwdta',    users + '\\hmwdta',  '');

// existing dvar gets replaced, absent dvar gets appended
hmwSetCfgValue(players2 + '\\config_mp.cfg', 'seta name', 'Player2');
hmwSetCfgValue(players2 + '\\config_mp.cfg', 'seta net_dummy', '1');

// re-seeding must not clobber the edit
hmwSeedFile(srcP2 + '\\config_mp.cfg', players2 + '\\config_mp.cfg');

// player 2 of a horizontal 2-way split on a 2560x1440 monitor
hmwApplyViewport(players2 + '\\config_mp.cfg', 2560, 720, 0, 720);

hmwWriteGuid(players2 + '\\hwgd.pf', '{00000000-0000-4000-8000-000000000002}');

hmwBackupIdentityOnce();
hmwWriteGuid(hmwRealAppData() + '\\hwgd.pf', '{00000000-0000-4000-8000-000000000002}');
hmwDelete(hmwRealAppData() + '\\hmw-key');
"@)

# --- assertions -------------------------------------------------------------

$fail = 0
function Check([string]$name, [scriptblock]$test) {
    $ok = $false
    try { $ok = [bool](& $test) } catch { $ok = $false }
    if ($ok) { "  PASS  $name" } else { "  FAIL  $name"; $script:fail++ }
}

$p2  = Join-Path $sandbox 'inst\players2'
$cfg = Get-Content -LiteralPath (Join-Path $p2 'config_mp.cfg')

"dry run in $sandbox"
Check 'hmwLog actually writes to the log file'  {
    (Test-Path -LiteralPath $logPath) -and
    (Get-Item -LiteralPath $logPath).Length -gt $logBefore -and
    (@(Get-Content -LiteralPath $logPath | Where-Object { $_ -match "^\[\d\d:\d\d:\d\d\] $logMarker$" }).Count -eq 1)
}
Check 'players2 and players2\user created'      { (Test-Path (Join-Path $p2 'user')) }
Check 'config_mp.cfg seeded'                    { Test-Path (Join-Path $p2 'config_mp.cfg') }
Check 'favourites.json created as []'           { (Get-Content -LiteralPath (Join-Path $p2 'favourites.json') -Raw) -eq '[]' }
Check 'history.json seeded from install'        { (Get-Content -LiteralPath (Join-Path $p2 'history.json') -Raw) -eq '{}' }
Check 'user\hmwcdta seeded from install'        { (Get-Content -LiteralPath (Join-Path $p2 'user\hmwcdta') -Raw) -eq 'cdta' }
Check 'user\hmwdta created empty'               { (Get-Item -LiteralPath (Join-Path $p2 'user\hmwdta')).Length -eq 0 }
Check 'existing seta name replaced'             { ($cfg | Where-Object { $_ -eq 'seta name "Player2"' }).Count -eq 1 }
Check 'old seta name gone'                      { ($cfg | Where-Object { $_ -like 'seta name "gargr"*' }).Count -eq 0 }
Check 'missing dvar appended'                   { ($cfg | Where-Object { $_ -eq 'seta net_dummy "1"' }).Count -eq 1 }
Check 'other cfg lines preserved'               { ($cfg | Where-Object { $_ -eq 'seta com_maxfps "0"' }).Count -eq 1 }
Check 'reseed did not clobber the edit'         { ($cfg | Where-Object { $_ -eq 'seta name "Player2"' }).Count -eq 1 }
# --- viewport: the second instance was cut off at the split boundary ---------
function CfgLine([string]$key) { @($cfg | Where-Object { $_ -like "$key `"*" }) }

Check 'r_mode set to the split size'            { (CfgLine 'seta r_mode') -eq 'seta r_mode "2560x720"' }
Check 'full-screen r_mode is gone'              { @($cfg | Where-Object { $_ -like '*2560x1440*' }).Count -eq 0 }
Check 'r_fullscreen off'                        { (CfgLine 'seta r_fullscreen') -eq 'seta r_fullscreen "0"' }
Check 'r_fullscreenWindow off'                  { (CfgLine 'seta r_fullscreenWindow') -eq 'seta r_fullscreenWindow "0"' }
# "seta r_fullscreen " must not also match "seta r_fullscreenWindow ", nor
# "seta r_renderResolutionNative " match "seta r_renderResolution ".
Check 'r_fullscreen written exactly once'       { (CfgLine 'seta r_fullscreen').Count -eq 1 }
Check 'r_fullscreenWindow written exactly once' { (CfgLine 'seta r_fullscreenWindow').Count -eq 1 }
Check 'r_renderResolutionNative on'             { (CfgLine 'seta r_renderResolutionNative') -eq 'seta r_renderResolutionNative "1"' }
Check 'r_renderResolution left untouched'       { (CfgLine 'seta r_renderResolution') -eq 'seta r_renderResolution "3.6864"' }
Check 'r_aspectRatio auto'                      { (CfgLine 'seta r_aspectRatio') -eq 'seta r_aspectRatio "auto"' }
Check 'vid_xpos is the slice origin'            { (CfgLine 'seta vid_xpos') -eq 'seta vid_xpos "0"' }
Check 'vid_ypos is the slice origin'            { (CfgLine 'seta vid_ypos') -eq 'seta vid_ypos "720"' }
Check 'no dvar duplicated by the viewport pass' {
    $keys = $cfg | Where-Object { $_ -match '^seta \S+ ' } | ForEach-Object { ($_ -split ' ')[1] }
    ($keys | Group-Object | Where-Object { $_.Count -gt 1 }).Count -eq 0
}

# A missing viewport must leave the config alone rather than write "0x0" or "NaN".
$degenerate = Join-Path $sandbox 'degenerate.cfg'
Copy-Item -LiteralPath (Join-Path $srcP2 'config_mp.cfg') -Destination $degenerate
[void]$engine.Execute("var degenOk = hmwApplyViewport(" + (ConvertTo-Json $degenerate) + ", 0, 0, undefined, undefined);")
$applied = $engine.GetValue('degenOk').ToObject()
$degenCfg = Get-Content -LiteralPath $degenerate
Check 'zero viewport reports failure'           { $applied -eq $false }
Check 'zero viewport writes nothing'            {
    (@($degenCfg | Where-Object { $_ -eq 'seta r_mode "2560x1440"' }).Count -eq 1) -and
    (@($degenCfg | Where-Object { $_ -like '*0x0*' -or $_ -like '*NaN*' }).Count -eq 0)
}
# A missing position must not become "NaN" when the size is valid.
$posCfgPath = Join-Path $sandbox 'pos.cfg'
Copy-Item -LiteralPath (Join-Path $srcP2 'config_mp.cfg') -Destination $posCfgPath
[void]$engine.Execute("hmwApplyViewport(" + (ConvertTo-Json $posCfgPath) + ", 1280, 1440, undefined, undefined);")
$posCfg = Get-Content -LiteralPath $posCfgPath
Check 'missing position falls back to 0'        {
    (@($posCfg | Where-Object { $_ -eq 'seta vid_xpos "0"' }).Count -eq 1) -and
    (@($posCfg | Where-Object { $_ -like '*NaN*' }).Count -eq 0)
}

# The production shape: Nucleus supplies Width/Height/PosX/PosY as CLR Int32,
# not JS numbers. If Jint surfaced those as anything parseInt cannot read, the
# viewport pass would silently no-op in the real handler while still passing
# every literal-driven test above.
Add-Type -TypeDefinition 'public class HmwCtxStub { public int Width {get;set;} public int Height {get;set;} public int PosX {get;set;} public int PosY {get;set;} }' -ErrorAction SilentlyContinue
$clrCfgPath = Join-Path $sandbox 'clrctx.cfg'
Copy-Item -LiteralPath (Join-Path $srcP2 'config_mp.cfg') -Destination $clrCfgPath
[void]$engine.SetValue('Context', (New-Object HmwCtxStub -Property @{ Width = 1280; Height = 1440; PosX = 1280; PosY = 0 }))
[void]$engine.Execute("var clrOk = hmwApplyViewport(" + (ConvertTo-Json $clrCfgPath) +
    ", Context.Width, Context.Height, Context.PosX, Context.PosY);")
$clrCfg = Get-Content -LiteralPath $clrCfgPath
Check 'CLR Int32 context is a JS number'        { $engine.GetValue('clrOk').ToObject() -eq $true }
Check 'CLR Int32 context writes the viewport'   {
    (@($clrCfg | Where-Object { $_ -eq 'seta r_mode "1280x1440"' }).Count -eq 1) -and
    (@($clrCfg | Where-Object { $_ -eq 'seta vid_xpos "1280"' }).Count -eq 1) -and
    (@($clrCfg | Where-Object { $_ -eq 'seta vid_ypos "0"' }).Count -eq 1) -and
    (@($clrCfg | Where-Object { $_ -like '*NaN*' }).Count -eq 0)
}

Check 'hwgd.pf is exactly 39 bytes'             { (Get-Item -LiteralPath (Join-Path $p2 'hwgd.pf')).Length -eq 39 }
Check 'hwgd.pf ends with a single 0x00'         {
    $b = [IO.File]::ReadAllBytes((Join-Path $p2 'hwgd.pf'))
    $b[38] -eq 0 -and $b[37] -eq [byte][char]'}'
}
Check 'hwgd.pf has no BOM'                      { ([IO.File]::ReadAllBytes((Join-Path $p2 'hwgd.pf')))[0] -eq [byte][char]'{' }
Check 'hwgd.pf backed up before overwrite'      { (Get-Content -LiteralPath (Join-Path $sandbox 'appdata\hwgd.pf.nucleus-original') -Raw) -eq 'REAL-GUID' }
Check 'hmw-key backed up before deletion'       { (Get-Content -LiteralPath (Join-Path $sandbox 'appdata\hmw-key.nucleus-original') -Raw) -eq 'REAL-KEY' }
Check 'no backup made for absent hmw-key.pub'   { -not (Test-Path (Join-Path $sandbox 'appdata\hmw-key.pub.nucleus-original')) }
Check 'guest identity was actually mutated'     {
    (Get-Item -LiteralPath (Join-Path $sandbox 'appdata\hwgd.pf')).Length -eq 39 -and
    -not (Test-Path (Join-Path $sandbox 'appdata\hmw-key'))
}

# restore, then assert the original identity is byte-identical again
[void]$engine.Execute('hmwRestoreIdentity();')
Check 'restore brings hwgd.pf back'             { (Get-Content -LiteralPath (Join-Path $sandbox 'appdata\hwgd.pf') -Raw) -eq 'REAL-GUID' }
Check 'restore brings hmw-key back'             { (Get-Content -LiteralPath (Join-Path $sandbox 'appdata\hmw-key') -Raw) -eq 'REAL-KEY' }
Check 'backups removed after restore'           { -not (Test-Path (Join-Path $sandbox 'appdata\hwgd.pf.nucleus-original')) }
[void]$engine.Execute('hmwRestoreIdentity();')
Check 'second restore is a no-op'               { (Get-Content -LiteralPath (Join-Path $sandbox 'appdata\hwgd.pf') -Raw) -eq 'REAL-GUID' }

Remove-Item -LiteralPath $sandbox -Recurse -Force -ErrorAction SilentlyContinue

if ($fail -gt 0) { "$fail check(s) failed"; exit 1 } else { 'all checks passed'; exit 0 }
