# Runs the helper prelude of HorizonMW.js under the same Jint engine Nucleus uses,
# against a throwaway sandbox, and asserts the byte-level and text-level behaviour
# that the handler depends on. Touches nothing outside the sandbox.

$ErrorActionPreference = 'Stop'

$repo   = Split-Path -Parent $PSScriptRoot
$jint   = 'C:\NucleusCoop\Jint.dll'
$sandbox = Join-Path $env:TEMP ('hmw-dryrun-' + [Guid]::NewGuid().ToString('N').Substring(0, 8))

Add-Type -Path $jint

# Take only the helper prelude, i.e. everything before the Game definition.
$src    = [IO.File]::ReadAllText((Join-Path $repo 'HorizonMW.js'))
$marker = '// Game definition'
$cut    = $src.IndexOf($marker)
if ($cut -lt 0) { throw "marker '$marker' not found in HorizonMW.js" }
$prelude = $src.Substring(0, $cut)

New-Item -ItemType Directory -Force -Path (Join-Path $sandbox 'src\user'), (Join-Path $sandbox 'inst'), (Join-Path $sandbox 'appdata') | Out-Null

# A source install to seed from: config has a name line, no favourites.json.
$srcP2 = Join-Path $sandbox 'src'
@(
    '// generated by Call of Duty: MWR - do not modify',
    'seta cg_drawFPS "0"',
    'seta cg_drawFPSLabels "1"',
    'seta cg_infobar_fps "0"',
    'seta name "gargr"',
    'seta com_maxfps "0"',
    # The real render dvars, verbatim from the install, so the viewport test runs
    # against the exact strings and prefix collisions the handler will meet.
    'seta r_aspectRatio "auto"',
    'seta r_renderResolutionNative "0"',
    'seta r_renderResolution "3.6864"',
    'seta vid_xpos "-1"',
    'seta vid_ypos "-1"',
    'seta r_fullscreen "1"',
    'seta r_fullscreenWindow "1"',
    'seta r_mode "2560x1440"'
) -join "`r`n" | Set-Content -LiteralPath (Join-Path $srcP2 'config_mp.cfg') -Encoding Ascii -NoNewline
'{}' | Set-Content -LiteralPath (Join-Path $srcP2 'history.json') -Encoding Ascii -NoNewline
'cdta' | Set-Content -LiteralPath (Join-Path $srcP2 'user\hmwcdta') -Encoding Ascii -NoNewline

# A pre-existing identity to be backed up and restored.
$appdata = Join-Path $sandbox 'appdata'
'REAL-GUID' | Set-Content -LiteralPath (Join-Path $appdata 'hwgd.pf') -Encoding Ascii -NoNewline
'REAL-KEY'  | Set-Content -LiteralPath (Join-Path $appdata 'hmw-key') -Encoding Ascii -NoNewline

$engine = New-Object Jint.Engine ([Action[Jint.Options]] { param($o) [void]$o.AllowClr() })
[void]$engine.Execute($prelude)

# hmwLog swallows its own errors, so prove it actually writes. Jint cannot call
# System.DateTime.Now.ToString(), which once made every log write a silent no-op.
$logPath = Join-Path $env:TEMP 'HorizonMWHandler.log'
$logBefore = if (Test-Path -LiteralPath $logPath) { (Get-Item -LiteralPath $logPath).Length } else { 0 }
$logMarker = 'dryrun-marker-' + [Guid]::NewGuid().ToString('N').Substring(0, 8)
[void]$engine.Execute("hmwLog(" + (ConvertTo-Json $logMarker) + ");")

# Point the identity helpers at the sandbox instead of the real %LOCALAPPDATA%.
[void]$engine.Execute("hmwRealAppData = function () { return " + (ConvertTo-Json $appdata) + "; };")

$jsSandbox = ConvertTo-Json $sandbox
[void]$engine.Execute(@"
var SB      = $jsSandbox;
var srcP2   = SB + '\\src';
var inst    = SB + '\\inst';
var players2 = inst + '\\players2';
var users    = players2 + '\\user';

hmwEnsureDir(players2);
hmwEnsureDir(users);

hmwSeedFile(srcP2 + '\\config_mp.cfg', players2 + '\\config_mp.cfg');
hmwSeedOrCreate(srcP2 + '\\favourites.json', players2 + '\\favourites.json', '[]');
hmwSeedOrCreate(srcP2 + '\\history.json',    players2 + '\\history.json',    '[]');
hmwSeedOrCreate(srcP2 + '\\user\\hmwcdta',   users + '\\hmwcdta', '');
hmwSeedOrCreate(srcP2 + '\\user\\hmwdta',    users + '\\hmwdta',  '');

// existing dvar gets replaced, absent dvar gets appended
hmwSetCfgValue(players2 + '\\config_mp.cfg', 'seta name', 'Player2');
hmwSetCfgValue(players2 + '\\config_mp.cfg', 'seta net_dummy', '1');

// re-seeding must not clobber the edit
hmwSeedFile(srcP2 + '\\config_mp.cfg', players2 + '\\config_mp.cfg');

hmwApplyWindowedMode(players2 + '\\config_mp.cfg');
hmwApplyFpsCounter(players2 + '\\config_mp.cfg');

hmwWriteGuid(players2 + '\\hwgd.pf', '{00000000-0000-4000-8000-000000000002}');

hmwBackupIdentityOnce();
hmwWriteGuid(hmwRealAppData() + '\\hwgd.pf', '{00000000-0000-4000-8000-000000000002}');
hmwDelete(hmwRealAppData() + '\\hmw-key');
"@)

# --- assertions -------------------------------------------------------------

$fail = 0
function Check([string]$name, [scriptblock]$test) {
    $ok = $false
    try { $ok = [bool](& $test) } catch { $ok = $false }
    if ($ok) { "  PASS  $name" } else { "  FAIL  $name"; $script:fail++ }
}

$p2  = Join-Path $sandbox 'inst\players2'
$cfg = Get-Content -LiteralPath (Join-Path $p2 'config_mp.cfg')

"dry run in $sandbox"
Check 'hmwLog actually writes to the log file'  {
    (Test-Path -LiteralPath $logPath) -and
    (Get-Item -LiteralPath $logPath).Length -gt $logBefore -and
    (@(Get-Content -LiteralPath $logPath | Where-Object { $_ -match "^\[\d\d:\d\d:\d\d\] $logMarker$" }).Count -eq 1)
}
Check 'players2 and players2\user created'      { (Test-Path (Join-Path $p2 'user')) }
Check 'config_mp.cfg seeded'                    { Test-Path (Join-Path $p2 'config_mp.cfg') }
Check 'favourites.json created as []'           { (Get-Content -LiteralPath (Join-Path $p2 'favourites.json') -Raw) -eq '[]' }
Check 'history.json seeded from install'        { (Get-Content -LiteralPath (Join-Path $p2 'history.json') -Raw) -eq '{}' }
Check 'user\hmwcdta seeded from install'        { (Get-Content -LiteralPath (Join-Path $p2 'user\hmwcdta') -Raw) -eq 'cdta' }
Check 'user\hmwdta created empty'               { (Get-Item -LiteralPath (Join-Path $p2 'user\hmwdta')).Length -eq 0 }
Check 'existing seta name replaced'             { ($cfg | Where-Object { $_ -eq 'seta name "Player2"' }).Count -eq 1 }
Check 'old seta name gone'                      { ($cfg | Where-Object { $_ -like 'seta name "gargr"*' }).Count -eq 0 }
Check 'missing dvar appended'                   { ($cfg | Where-Object { $_ -eq 'seta net_dummy "1"' }).Count -eq 1 }
Check 'other cfg lines preserved'               { ($cfg | Where-Object { $_ -eq 'seta com_maxfps "0"' }).Count -eq 1 }
Check 'reseed did not clobber the edit'         { ($cfg | Where-Object { $_ -eq 'seta name "Player2"' }).Count -eq 1 }
# --- windowed mode: instances were cut off, then crashed during the resize ---
function CfgLine([string]$key) { @($cfg | Where-Object { $_ -like "$key `"*" }) }

# r_mode only accepts an enumerated display mode, so a split size like 2560x720
# is reset to native by the game. Writing it was useless; writing it again would
# be a regression.
Check 'r_mode left at the display mode'         { (CfgLine 'seta r_mode') -eq 'seta r_mode "2560x1440"' }
# Pre-positioning put a native-height window half off-screen, which is the only
# value that differed between the instance that crashed and the one that did not.
Check 'vid_xpos pinned to stock -1'             { (CfgLine 'seta vid_xpos') -eq 'seta vid_xpos "-1"' }
Check 'vid_ypos pinned to stock -1'             { (CfgLine 'seta vid_ypos') -eq 'seta vid_ypos "-1"' }
Check 'r_fullscreen off'                        { (CfgLine 'seta r_fullscreen') -eq 'seta r_fullscreen "0"' }
Check 'r_fullscreenWindow off'                  { (CfgLine 'seta r_fullscreenWindow') -eq 'seta r_fullscreenWindow "0"' }
# "seta r_fullscreen " must not also match "seta r_fullscreenWindow ", nor
# "seta r_renderResolutionNative " match "seta r_renderResolution ".
Check 'r_fullscreen written exactly once'       { (CfgLine 'seta r_fullscreen').Count -eq 1 }
Check 'r_fullscreenWindow written exactly once' { (CfgLine 'seta r_fullscreenWindow').Count -eq 1 }
Check 'r_renderResolutionNative on'             { (CfgLine 'seta r_renderResolutionNative') -eq 'seta r_renderResolutionNative "1"' }
Check 'r_renderResolution left untouched'       { (CfgLine 'seta r_renderResolution') -eq 'seta r_renderResolution "3.6864"' }
Check 'r_aspectRatio auto'                      { (CfgLine 'seta r_aspectRatio') -eq 'seta r_aspectRatio "auto"' }

# --- FPS counter -------------------------------------------------------------
# Toggling it in-game and diffing two instances showed HMW writes cg_infobar_fps.
Check 'cg_infobar_fps turned on'                { (CfgLine 'seta cg_infobar_fps') -eq 'seta cg_infobar_fps "1"' }
Check 'cg_infobar_fps written exactly once'     { (CfgLine 'seta cg_infobar_fps').Count -eq 1 }
# The stock dvar is not what HMW's UI drives, so touching it would be a no-op at
# best and a second overlapping readout at worst.
Check 'stock cg_drawFPS left alone'             { (CfgLine 'seta cg_drawFPS') -eq 'seta cg_drawFPS "0"' }
# "seta cg_drawFPS " is a prefix of "seta cg_drawFPSLabels ".
Check 'cg_drawFPSLabels not collided with'      { (CfgLine 'seta cg_drawFPSLabels') -eq 'seta cg_drawFPSLabels "1"' }
Check 'cg_drawFPSLabels still exactly once'     { (CfgLine 'seta cg_drawFPSLabels').Count -eq 1 }
Check 'no dvar duplicated by the windowed pass' {
    $keys = $cfg | Where-Object { $_ -match '^seta \S+ ' } | ForEach-Object { ($_ -split ' ')[1] }
    ($keys | Group-Object | Where-Object { $_.Count -gt 1 }).Count -eq 0
}
# Nothing geometry dependent may be written, so two instances with different
# slices must end up with byte-identical render settings.
$aPath = Join-Path $sandbox 'a.cfg'; $bPath = Join-Path $sandbox 'b.cfg'
Copy-Item -LiteralPath (Join-Path $srcP2 'config_mp.cfg') -Destination $aPath
Copy-Item -LiteralPath (Join-Path $srcP2 'config_mp.cfg') -Destination $bPath
[void]$engine.Execute("hmwApplyWindowedMode(" + (ConvertTo-Json $aPath) + ");")
[void]$engine.Execute("hmwApplyWindowedMode(" + (ConvertTo-Json $bPath) + ");")
Check 'windowed pass is geometry independent'    {
    (Get-FileHash $aPath).Hash -eq (Get-FileHash $bPath).Hash
}
Check 'windowed pass is idempotent'              {
    $before = (Get-FileHash $aPath).Hash
    [void]$engine.Execute("hmwApplyWindowedMode(" + (ConvertTo-Json $aPath) + ");")
    (Get-FileHash $aPath).Hash -eq $before
}

# An instance set up by the version that crashed still has the off-screen
# position on disk. The handler has to actively undo it, not merely stop writing
# it, or the crash reproduces on the next launch.
$stalePath = Join-Path $sandbox 'stale.cfg'
@(
    'seta r_fullscreen "1"',
    'seta r_fullscreenWindow "1"',
    'seta r_mode "2560x1440"',
    'seta r_aspectRatio "auto"',
    'seta r_renderResolutionNative "0"',
    'seta vid_xpos "0"',
    'seta vid_ypos "720"'
) -join "`r`n" | Set-Content -LiteralPath $stalePath -Encoding Ascii -NoNewline
[void]$engine.Execute("hmwApplyWindowedMode(" + (ConvertTo-Json $stalePath) + ");")
$staleCfg = Get-Content -LiteralPath $stalePath
Check 'stale off-screen vid_ypos is undone'      {
    (@($staleCfg | Where-Object { $_ -eq 'seta vid_ypos "-1"' }).Count -eq 1) -and
    (@($staleCfg | Where-Object { $_ -eq 'seta vid_ypos "720"' }).Count -eq 0)
}
Check 'stale fullscreen flags are undone'        {
    (@($staleCfg | Where-Object { $_ -eq 'seta r_fullscreen "0"' }).Count -eq 1) -and
    (@($staleCfg | Where-Object { $_ -eq 'seta r_fullscreenWindow "0"' }).Count -eq 1)
}

# HMW_SHOW_FPS = false must leave the player's own in-game choice untouched.
$optOutPath = Join-Path $sandbox 'nofps.cfg'
'seta cg_infobar_fps "0"' | Set-Content -LiteralPath $optOutPath -Encoding Ascii -NoNewline
[void]$engine.Execute("HMW_SHOW_FPS = false; var offOk = hmwApplyFpsCounter(" + (ConvertTo-Json $optOutPath) + ");")
Check 'HMW_SHOW_FPS false reports skipped'       { $engine.GetValue('offOk').ToObject() -eq $false }
Check 'HMW_SHOW_FPS false writes nothing'        {
    (Get-Content -LiteralPath $optOutPath -Raw).Trim() -eq 'seta cg_infobar_fps "0"'
}
[void]$engine.Execute('HMW_SHOW_FPS = true;')

# --- graphics presets --------------------------------------------------------
$presetDir = Join-Path $sandbox 'Graphics'
New-Item -ItemType Directory -Path $presetDir -Force | Out-Null
@(
    '// a comment',
    '# another comment',
    '',
    '   ',
    'seta r_picmip "3"',
    'seta sm_enable "0"',
    'r_texFilterAnisoMax "1"',              # bare form, no seta
    'seta sm_tileResolution "High"',        # string value
    'seta r_fullscreen "1"',               # blocked, would break split-screen
    'seta vid_ypos "720"',                 # blocked, this exact value crashed an instance
    'seta name "hacker"',                  # blocked, would collapse profiles
    'total garbage line with no value'     # tolerated, must not throw
) | Set-Content -LiteralPath (Join-Path $presetDir 'Low.cfg') -Encoding Ascii

$instCfg = Join-Path $p2 'config_mp.cfg'

function ApplyPreset([string]$preset, [string]$cfg) {
    $js = "var applied = hmwApplyGraphicsPreset(" + (ConvertTo-Json $cfg) + ", " +
          (ConvertTo-Json $preset) + ", " + (ConvertTo-Json $presetDir) + ");"
    [void]$engine.Execute($js)
    return [int]$engine.GetValue('applied').ToObject()
}
function PresetCfg([string]$cfg, [string]$key) {
    @(Get-Content -LiteralPath $cfg | Where-Object { $_ -like "$key *" })
}

# "Default" must be a complete no-op, since it is the default selection.
$defCfg = Join-Path $sandbox 'preset-default.cfg'
Copy-Item -LiteralPath $instCfg -Destination $defCfg -Force
$defBefore = Get-Content -LiteralPath $defCfg -Raw
$defCount = ApplyPreset 'Default' $defCfg
Check 'Default preset applies nothing'           { $defCount -eq 0 }
Check 'Default preset changes no bytes'          { (Get-Content -LiteralPath $defCfg -Raw) -eq $defBefore }

# An unknown or missing preset must also change nothing rather than throw.
$missCfg = Join-Path $sandbox 'preset-missing.cfg'
Copy-Item -LiteralPath $instCfg -Destination $missCfg -Force
$missBefore = Get-Content -LiteralPath $missCfg -Raw
$missCount = ApplyPreset 'Nonexistent' $missCfg
Check 'missing preset file applies nothing'      { $missCount -eq 0 }
Check 'missing preset file changes no bytes'     { (Get-Content -LiteralPath $missCfg -Raw) -eq $missBefore }
Check 'missing preset file is logged'            {
    (Get-Content -LiteralPath $logPath -Raw) -match "graphics preset 'Nonexistent' has no file"
}

# The real thing, over a config that already went through the windowed pass.
$lowCfg = Join-Path $sandbox 'preset-low.cfg'
Copy-Item -LiteralPath $instCfg -Destination $lowCfg -Force
$lowCount = ApplyPreset 'Low' $lowCfg
Check 'Low preset applied 4 allowed dvars'       { $lowCount -eq 4 }
Check 'preset set r_picmip'                      { (PresetCfg $lowCfg 'seta r_picmip') -contains 'seta r_picmip "3"' }
Check 'preset set sm_enable'                     { (PresetCfg $lowCfg 'seta sm_enable') -eq 'seta sm_enable "0"' }
Check 'preset honoured the bare no-seta form'    { (PresetCfg $lowCfg 'seta r_texFilterAnisoMax') -eq 'seta r_texFilterAnisoMax "1"' }
Check 'preset kept a string value intact'        { (PresetCfg $lowCfg 'seta sm_tileResolution') -eq 'seta sm_tileResolution "High"' }
# A looser regex once parsed the prose line as a dvar named "total" and wrote it
# straight into config_mp.cfg.
Check 'prose line did not become a dvar'         { (PresetCfg $lowCfg 'seta total').Count -eq 0 }
Check 'unparseable line counted in the log'      {
    (Get-Content -LiteralPath $logPath -Raw) -match 'skipped 1 unparseable line'
}

# The blocklist is the guard that stops an edited preset undoing the two fixes
# that took a crash each to find.
Check 'blocked r_fullscreen stayed off'          { (PresetCfg $lowCfg 'seta r_fullscreen') -eq 'seta r_fullscreen "0"' }
Check 'blocked vid_ypos stayed at -1'            { (PresetCfg $lowCfg 'seta vid_ypos') -eq 'seta vid_ypos "-1"' }
Check 'blocked name untouched'                   { (PresetCfg $lowCfg 'seta name') -eq 'seta name "Player2"' }
# Non-vacuity: with the blocklist emptied the same preset file must actually
# break windowing, otherwise the three checks above prove nothing.
Check 'blocklist is what stops r_fullscreen'     {
    $unguarded = Join-Path $sandbox 'preset-unguarded.cfg'
    Copy-Item -LiteralPath $instCfg -Destination $unguarded -Force
    [void]$engine.Execute('var savedBlocked = HMW_PRESET_BLOCKED; HMW_PRESET_BLOCKED = [];')
    [void](ApplyPreset 'Low' $unguarded)
    [void]$engine.Execute('HMW_PRESET_BLOCKED = savedBlocked;')
    ((PresetCfg $unguarded 'seta r_fullscreen') -eq 'seta r_fullscreen "1"') -and
    ((PresetCfg $unguarded 'seta vid_ypos') -eq 'seta vid_ypos "720"') -and
    ((PresetCfg $unguarded 'seta name') -eq 'seta name "hacker"')
}
Check 'blocklist restored after that check'      {
    [void]$engine.Execute('var blockedCount = HMW_PRESET_BLOCKED.length;')
    [int]$engine.GetValue('blockedCount').ToObject() -eq 6
}
Check 'blocked dvars are logged'                 {
    (Get-Content -LiteralPath $logPath -Raw) -match 'ignored r_fullscreen, vid_ypos, name'
}
# r_picmip is a prefix of r_picmip_bump, and the preset only names the short one.
Check 'preset did not create r_picmip_bump'      { (PresetCfg $lowCfg 'seta r_picmip_bump').Count -eq 0 }
Check 'preset duplicated no dvar'                {
    $keys = Get-Content -LiteralPath $lowCfg | Where-Object { $_ -match '^seta (\S+)' } |
            ForEach-Object { ($_ -split ' ')[1] }
    ($keys | Group-Object | Where-Object Count -gt 1).Count -eq 0
}
Check 'preset is idempotent'                     {
    $once = Get-Content -LiteralPath $lowCfg -Raw
    [void](ApplyPreset 'Low' $lowCfg)
    (Get-Content -LiteralPath $lowCfg -Raw) -eq $once
}

# Every shipped preset must parse, apply cleanly, and never trip the blocklist.
$shippedDir = Join-Path (Split-Path -Parent $PSScriptRoot) 'HorizonMW\Graphics'
foreach ($name in @('Low', 'Medium', 'High', 'Extra')) {
    $shipCfg = Join-Path $sandbox "shipped-$name.cfg"
    Copy-Item -LiteralPath $instCfg -Destination $shipCfg -Force
    $js = "var n = hmwApplyGraphicsPreset(" + (ConvertTo-Json $shipCfg) + ", " +
          (ConvertTo-Json $name) + ", " + (ConvertTo-Json $shippedDir) + ");"
    [void]$engine.Execute($js)
    $n = [int]$engine.GetValue('n').ToObject()
    Check "shipped $name applies dvars"          { $n -ge 8 }
    Check "shipped $name keeps windowing intact" {
        ((PresetCfg $shipCfg 'seta r_fullscreen') -eq 'seta r_fullscreen "0"') -and
        ((PresetCfg $shipCfg 'seta vid_ypos') -eq 'seta vid_ypos "-1"') -and
        ((PresetCfg $shipCfg 'seta name') -eq 'seta name "Player2"')
    }
    Check "shipped $name duplicates nothing"     {
        $keys = Get-Content -LiteralPath $shipCfg | Where-Object { $_ -match '^seta (\S+)' } |
                ForEach-Object { ($_ -split ' ')[1] }
        ($keys | Group-Object | Where-Object Count -gt 1).Count -eq 0
    }
}
Check 'dropdown names all have a preset file'    {
    $declared = ([regex]::Match($src,
        'HMW_GRAPHICS_PRESETS\s*=\s*\[(.*?)\]').Groups[1].Value -split ',') |
        ForEach-Object { $_.Trim().Trim('"') } | Where-Object { $_ -and $_ -ne 'Default' }
    $missing = $declared | Where-Object { -not (Test-Path (Join-Path $shippedDir "$_.cfg")) }
    (@($declared).Count -eq 4) -and (@($missing).Count -eq 0)
}

Check 'hwgd.pf is exactly 39 bytes'             { (Get-Item -LiteralPath (Join-Path $p2 'hwgd.pf')).Length -eq 39 }
Check 'hwgd.pf ends with a single 0x00'         {
    $b = [IO.File]::ReadAllBytes((Join-Path $p2 'hwgd.pf'))
    $b[38] -eq 0 -and $b[37] -eq [byte][char]'}'
}
Check 'hwgd.pf has no BOM'                      { ([IO.File]::ReadAllBytes((Join-Path $p2 'hwgd.pf')))[0] -eq [byte][char]'{' }
Check 'hwgd.pf backed up before overwrite'      { (Get-Content -LiteralPath (Join-Path $sandbox 'appdata\hwgd.pf.nucleus-original') -Raw) -eq 'REAL-GUID' }
Check 'hmw-key backed up before deletion'       { (Get-Content -LiteralPath (Join-Path $sandbox 'appdata\hmw-key.nucleus-original') -Raw) -eq 'REAL-KEY' }
Check 'no backup made for absent hmw-key.pub'   { -not (Test-Path (Join-Path $sandbox 'appdata\hmw-key.pub.nucleus-original')) }
Check 'guest identity was actually mutated'     {
    (Get-Item -LiteralPath (Join-Path $sandbox 'appdata\hwgd.pf')).Length -eq 39 -and
    -not (Test-Path (Join-Path $sandbox 'appdata\hmw-key'))
}

# restore, then assert the original identity is byte-identical again
[void]$engine.Execute('hmwRestoreIdentity();')
Check 'restore brings hwgd.pf back'             { (Get-Content -LiteralPath (Join-Path $sandbox 'appdata\hwgd.pf') -Raw) -eq 'REAL-GUID' }
Check 'restore brings hmw-key back'             { (Get-Content -LiteralPath (Join-Path $sandbox 'appdata\hmw-key') -Raw) -eq 'REAL-KEY' }
Check 'backups removed after restore'           { -not (Test-Path (Join-Path $sandbox 'appdata\hwgd.pf.nucleus-original')) }
[void]$engine.Execute('hmwRestoreIdentity();')
Check 'second restore is a no-op'               { (Get-Content -LiteralPath (Join-Path $sandbox 'appdata\hwgd.pf') -Raw) -eq 'REAL-GUID' }

Remove-Item -LiteralPath $sandbox -Recurse -Force -ErrorAction SilentlyContinue

if ($fail -gt 0) { "$fail check(s) failed"; exit 1 } else { 'all checks passed'; exit 0 }
