# Runs the helper prelude of HorizonMW.js under the same Jint engine Nucleus uses,
# against a throwaway sandbox, and asserts the byte-level and text-level behaviour
# that the handler depends on. Touches nothing outside the sandbox.

$ErrorActionPreference = 'Stop'

$repo   = Split-Path -Parent $PSScriptRoot
$jint   = 'C:\NucleusCoop\Jint.dll'
$sandbox = Join-Path $env:TEMP ('hmw-dryrun-' + [Guid]::NewGuid().ToString('N').Substring(0, 8))

Add-Type -Path $jint

# Take only the helper prelude, i.e. everything before the Game definition.
$src    = [IO.File]::ReadAllText((Join-Path $repo 'HorizonMW.js'))
$marker = '// Game definition'
$cut    = $src.IndexOf($marker)
if ($cut -lt 0) { throw "marker '$marker' not found in HorizonMW.js" }
$prelude = $src.Substring(0, $cut)

New-Item -ItemType Directory -Force -Path (Join-Path $sandbox 'src\user'), (Join-Path $sandbox 'inst'), (Join-Path $sandbox 'appdata') | Out-Null

# A source install to seed from: config has a name line, no favourites.json.
$srcP2 = Join-Path $sandbox 'src'
@(
    '// generated by Call of Duty: MWR - do not modify',
    'seta cg_drawFPS "0"',
    'seta cg_drawFPSLabels "1"',
    'seta cg_infobar_fps "0"',
    'seta name "gargr"',
    'seta com_maxfps "0"',
    # The real render dvars, verbatim from the install, so the viewport test runs
    # against the exact strings and prefix collisions the handler will meet.
    'seta r_aspectRatio "auto"',
    'seta r_renderResolutionNative "0"',
    'seta r_renderResolution "3.6864"',
    'seta vid_xpos "-1"',
    'seta vid_ypos "-1"',
    'seta r_fullscreen "1"',
    'seta r_fullscreenWindow "1"',
    'seta r_mode "2560x1440"',
    # Game-written values for dvars the presets manage. Selecting Default has to
    # restore these, so they have to exist in the install config to restore from.
    'seta r_picmip "0"',
    'seta sm_enable "1"',
    'seta r_texFilterAnisoMax "4"'
) -join "`r`n" | Set-Content -LiteralPath (Join-Path $srcP2 'config_mp.cfg') -Encoding Ascii -NoNewline
'{}' | Set-Content -LiteralPath (Join-Path $srcP2 'history.json') -Encoding Ascii -NoNewline
# A realistic keys_mp.cfg: the game's real header, the unbindall the bind has to
# land after, and the two F-key binds the game ships with.
@(
    '// generated by Call of Duty: MWR - do not modify',
    'unbindall',
    'bind BUTTON_A "+gostand"',
    'bind TAB "+scores"',
    'bind F1 "discord_accept"',
    'bind F2 "discord_deny"'
) -join "`r`n" | Set-Content -LiteralPath (Join-Path $srcP2 'keys_mp.cfg') -Encoding Ascii -NoNewline
'cdta' | Set-Content -LiteralPath (Join-Path $srcP2 'user\hmwcdta') -Encoding Ascii -NoNewline

# A pre-existing identity to be backed up and restored.
$appdata = Join-Path $sandbox 'appdata'
'REAL-GUID' | Set-Content -LiteralPath (Join-Path $appdata 'hwgd.pf') -Encoding Ascii -NoNewline
'REAL-KEY'  | Set-Content -LiteralPath (Join-Path $appdata 'hmw-key') -Encoding Ascii -NoNewline

$engine = New-Object Jint.Engine ([Action[Jint.Options]] { param($o) [void]$o.AllowClr() })
[void]$engine.Execute($prelude)

# hmwLog swallows its own errors, so prove it actually writes. Jint cannot call
# System.DateTime.Now.ToString(), which once made every log write a silent no-op.
$logPath = Join-Path $env:TEMP 'HorizonMWHandler.log'
$logBefore = if (Test-Path -LiteralPath $logPath) { (Get-Item -LiteralPath $logPath).Length } else { 0 }
$logMarker = 'dryrun-marker-' + [Guid]::NewGuid().ToString('N').Substring(0, 8)
[void]$engine.Execute("hmwLog(" + (ConvertTo-Json $logMarker) + ");")

# Point the identity helpers at the sandbox instead of the real %LOCALAPPDATA%.
[void]$engine.Execute("hmwRealAppData = function () { return " + (ConvertTo-Json $appdata) + "; };")

$jsSandbox = ConvertTo-Json $sandbox
[void]$engine.Execute(@"
var SB      = $jsSandbox;
var srcP2   = SB + '\\src';
var inst    = SB + '\\inst';
var players2 = inst + '\\players2';
var users    = players2 + '\\user';

hmwEnsureDir(players2);
hmwEnsureDir(users);

hmwSeedFile(srcP2 + '\\config_mp.cfg', players2 + '\\config_mp.cfg');
hmwSeedFile(srcP2 + '\\keys_mp.cfg',   players2 + '\\keys_mp.cfg');
hmwSeedOrCreate(srcP2 + '\\favourites.json', players2 + '\\favourites.json', '[]');
hmwSeedOrCreate(srcP2 + '\\history.json',    players2 + '\\history.json',    '[]');
hmwSeedOrCreate(srcP2 + '\\user\\hmwcdta',   users + '\\hmwcdta', '');
hmwSeedOrCreate(srcP2 + '\\user\\hmwdta',    users + '\\hmwdta',  '');

// existing dvar gets replaced, absent dvar gets appended
hmwSetCfgValue(players2 + '\\config_mp.cfg', 'seta name', 'Player2');
hmwSetCfgValue(players2 + '\\config_mp.cfg', 'seta net_dummy', '1');

// the guest's one-key connect bind, exactly as Play() writes it
hmwSetCfgValue(players2 + '\\keys_mp.cfg', 'bind ' + HMW_CONNECT_BIND_KEY,
               'connect 127.0.0.1:' + HMW_HOST_PORT);

// re-seeding must not clobber the edit
hmwSeedFile(srcP2 + '\\config_mp.cfg', players2 + '\\config_mp.cfg');

hmwApplyWindowedMode(players2 + '\\config_mp.cfg', srcP2 + '\\config_mp.cfg');
hmwApplyFpsCounter(players2 + '\\config_mp.cfg');

hmwWriteGuid(players2 + '\\hwgd.pf', '{00000000-0000-4000-8000-000000000002}');

hmwBackupIdentityOnce();
hmwWriteGuid(hmwRealAppData() + '\\hwgd.pf', '{00000000-0000-4000-8000-000000000002}');
hmwDelete(hmwRealAppData() + '\\hmw-key');
"@)

# --- assertions -------------------------------------------------------------

$fail = 0
function Check([string]$name, [scriptblock]$test) {
    $ok = $false
    try { $ok = [bool](& $test) } catch { $ok = $false }
    if ($ok) { "  PASS  $name" } else { "  FAIL  $name"; $script:fail++ }
}

$p2  = Join-Path $sandbox 'inst\players2'
$cfg = Get-Content -LiteralPath (Join-Path $p2 'config_mp.cfg')

"dry run in $sandbox"
Check 'hmwLog actually writes to the log file'  {
    (Test-Path -LiteralPath $logPath) -and
    (Get-Item -LiteralPath $logPath).Length -gt $logBefore -and
    (@(Get-Content -LiteralPath $logPath | Where-Object { $_ -match "^\[\d\d:\d\d:\d\d\] $logMarker$" }).Count -eq 1)
}
Check 'players2 and players2\user created'      { (Test-Path (Join-Path $p2 'user')) }
Check 'config_mp.cfg seeded'                    { Test-Path (Join-Path $p2 'config_mp.cfg') }
Check 'favourites.json created as []'           { (Get-Content -LiteralPath (Join-Path $p2 'favourites.json') -Raw) -eq '[]' }
Check 'history.json seeded from install'        { (Get-Content -LiteralPath (Join-Path $p2 'history.json') -Raw) -eq '{}' }
Check 'user\hmwcdta seeded from install'        { (Get-Content -LiteralPath (Join-Path $p2 'user\hmwcdta') -Raw) -eq 'cdta' }
Check 'user\hmwdta created empty'               { (Get-Item -LiteralPath (Join-Path $p2 'user\hmwdta')).Length -eq 0 }
Check 'existing seta name replaced'             { ($cfg | Where-Object { $_ -eq 'seta name "Player2"' }).Count -eq 1 }
Check 'old seta name gone'                      { ($cfg | Where-Object { $_ -like 'seta name "gargr"*' }).Count -eq 0 }
Check 'missing dvar appended'                   { ($cfg | Where-Object { $_ -eq 'seta net_dummy "1"' }).Count -eq 1 }
Check 'other cfg lines preserved'               { ($cfg | Where-Object { $_ -eq 'seta com_maxfps "0"' }).Count -eq 1 }
Check 'reseed did not clobber the edit'         { ($cfg | Where-Object { $_ -eq 'seta name "Player2"' }).Count -eq 1 }

# --- the guest's one-key connect bind ---------------------------------------
# The F2 watcher presses one key instead of typing into the console, which only
# works if the bind is really in keys_mp.cfg, after unbindall, and does not
# disturb the binds the game ships with.
$keys = Get-Content -LiteralPath (Join-Path $p2 'keys_mp.cfg')
Check 'connect bind written exactly once'       { ($keys | Where-Object { $_ -eq 'bind F3 "connect 127.0.0.1:27016"' }).Count -eq 1 }
Check 'connect bind lands after unbindall'      {
    $u = [array]::IndexOf($keys, 'unbindall')
    $b = ($keys | Select-String -SimpleMatch 'bind F3 "connect' | Select-Object -First 1).LineNumber - 1
    ($u -ge 0) -and ($b -gt $u)
}
Check "game's own F1/F2 binds untouched"        {
    ($keys | Where-Object { $_ -eq 'bind F1 "discord_accept"' }).Count -eq 1 -and
    ($keys | Where-Object { $_ -eq 'bind F2 "discord_deny"' }).Count -eq 1
}
Check 'no F3 bind existed to collide with'      { ($keys | Where-Object { $_ -like 'bind F3 *' }).Count -eq 1 }
Check 'watcher VK matches the handler bind key' {
    $w = Get-Content -LiteralPath (Join-Path $PSScriptRoot '..\HorizonMW\HMWConnectHotkey.ps1') -Raw
    # F3 is 0x72; a mismatch here would press the wrong key and silently do nothing.
    ($w -match "\`$ConnectBindKey\s*=\s*'F3'") -and ($w -match "\`$VK_CONNECT_BIND\s*=\s*0x72")
}
# --- windowed mode: instances were cut off, then crashed during the resize ---
function CfgLine([string]$key) { @($cfg | Where-Object { $_ -like "$key `"*" }) }

# r_mode only accepts an enumerated display mode, so a split size like 2560x720
# is reset to native by the game. Writing it was useless; writing it again would
# be a regression.
Check 'r_mode left at the display mode'         { (CfgLine 'seta r_mode') -eq 'seta r_mode "2560x1440"' }
# Pre-positioning put a native-height window half off-screen, which is the only
# value that differed between the instance that crashed and the one that did not.
Check 'vid_xpos pinned to stock -1'             { (CfgLine 'seta vid_xpos') -eq 'seta vid_xpos "-1"' }
Check 'vid_ypos pinned to stock -1'             { (CfgLine 'seta vid_ypos') -eq 'seta vid_ypos "-1"' }
Check 'r_fullscreen off'                        { (CfgLine 'seta r_fullscreen') -eq 'seta r_fullscreen "0"' }
Check 'r_fullscreenWindow off'                  { (CfgLine 'seta r_fullscreenWindow') -eq 'seta r_fullscreenWindow "0"' }
# "seta r_fullscreen " must not also match "seta r_fullscreenWindow ", nor
# "seta r_renderResolutionNative " match "seta r_renderResolution ".
Check 'r_fullscreen written exactly once'       { (CfgLine 'seta r_fullscreen').Count -eq 1 }
Check 'r_fullscreenWindow written exactly once' { (CfgLine 'seta r_fullscreenWindow').Count -eq 1 }
Check 'r_renderResolutionNative on'             { (CfgLine 'seta r_renderResolutionNative') -eq 'seta r_renderResolutionNative "1"' }
Check 'r_renderResolution left untouched'       { (CfgLine 'seta r_renderResolution') -eq 'seta r_renderResolution "3.6864"' }
Check 'r_aspectRatio auto'                      { (CfgLine 'seta r_aspectRatio') -eq 'seta r_aspectRatio "auto"' }

# --- FPS counter -------------------------------------------------------------
# Toggling it in-game and diffing two instances showed HMW writes cg_infobar_fps.
Check 'cg_infobar_fps turned on'                { (CfgLine 'seta cg_infobar_fps') -eq 'seta cg_infobar_fps "1"' }
Check 'cg_infobar_fps written exactly once'     { (CfgLine 'seta cg_infobar_fps').Count -eq 1 }
# The stock dvar is not what HMW's UI drives, so touching it would be a no-op at
# best and a second overlapping readout at worst.
Check 'stock cg_drawFPS left alone'             { (CfgLine 'seta cg_drawFPS') -eq 'seta cg_drawFPS "0"' }
# "seta cg_drawFPS " is a prefix of "seta cg_drawFPSLabels ".
Check 'cg_drawFPSLabels not collided with'      { (CfgLine 'seta cg_drawFPSLabels') -eq 'seta cg_drawFPSLabels "1"' }
Check 'cg_drawFPSLabels still exactly once'     { (CfgLine 'seta cg_drawFPSLabels').Count -eq 1 }
Check 'no dvar duplicated by the windowed pass' {
    $keys = $cfg | Where-Object { $_ -match '^seta \S+ ' } | ForEach-Object { ($_ -split ' ')[1] }
    ($keys | Group-Object | Where-Object { $_.Count -gt 1 }).Count -eq 0
}
# The render target is sized to the slice, so two instances with DIFFERENT slices
# must end up with byte-identical render settings.
#
# This was briefly replaced by the opposite assertion, that the render resolution
# follows the slice, while the handler wrote a per-slice megapixel count. That was
# measured as worth nothing, 3,737 MiB per instance before against 3,791 MiB after,
# and reverted, so the original assertion stands again. Anything geometry dependent
# in this file means the instances no longer share one render configuration.
$aPath = Join-Path $sandbox 'a.cfg'; $bPath = Join-Path $sandbox 'b.cfg'
$srcCfgPath = Join-Path $srcP2 'config_mp.cfg'
Copy-Item -LiteralPath (Join-Path $srcP2 'config_mp.cfg') -Destination $aPath
Copy-Item -LiteralPath (Join-Path $srcP2 'config_mp.cfg') -Destination $bPath
[void]$engine.Execute("hmwApplyWindowedMode(" + (ConvertTo-Json $aPath) + ", " + (ConvertTo-Json $srcCfgPath) + ");")
[void]$engine.Execute("hmwApplyWindowedMode(" + (ConvertTo-Json $bPath) + ", " + (ConvertTo-Json $srcCfgPath) + ");")
Check 'windowed pass is geometry independent'    {
    (Get-FileHash $aPath).Hash -eq (Get-FileHash $bPath).Hash
}
Check 'render resolution left native'            {
    (Get-Content -LiteralPath $aPath | Where-Object { $_ -like 'seta r_renderResolutionNative *' }) -eq 'seta r_renderResolutionNative "1"'
}
Check 'megapixel count not rewritten'            {
    (Get-Content -LiteralPath $aPath | Where-Object { $_ -like 'seta r_renderResolution *' }) -eq 'seta r_renderResolution "3.6864"'
}
# Every instance that ran the per-slice version has "0.5184" on disk, because the
# game accepted it and wrote it back out on exit. Pinning the native flag does not
# remove it, so the handler has to restore the install value actively.
Check 'per-slice residue is undone'              {
    $p = Join-Path $sandbox 'residue.cfg'
    Copy-Item -LiteralPath $srcCfgPath -Destination $p
    # Built in a variable, not inline: inside a method call PowerShell reads the comma
    # in -replace 'a','b' as an argument separator, so WriteAllLines gets three
    # arguments, throws, and the seeding silently does not happen.
    $seed = @(Get-Content -LiteralPath $p) -replace '^seta r_renderResolution "[^"]*"$', 'seta r_renderResolution "0.5184"'
    $seed = $seed -replace '^seta r_renderResolutionNative "[^"]*"$', 'seta r_renderResolutionNative "0"'
    Set-Content -LiteralPath $p -Value $seed -Encoding Ascii
    $seeded = @(Get-Content -LiteralPath $p | Where-Object { $_ -eq 'seta r_renderResolution "0.5184"' }).Count -eq 1
    [void]$engine.Execute("hmwApplyWindowedMode(" + (ConvertTo-Json $p) + ", " + (ConvertTo-Json $srcCfgPath) + ");")
    $c = Get-Content -LiteralPath $p
    $seeded -and
    (($c | Where-Object { $_ -like 'seta r_renderResolution *' }) -eq 'seta r_renderResolution "3.6864"') -and
    (($c | Where-Object { $_ -like 'seta r_renderResolutionNative *' }) -eq 'seta r_renderResolutionNative "1"') -and
    (@($c | Where-Object { $_ -like 'seta r_renderResolution *' }).Count -eq 1)
}
Check 'no install config means no rewrite'       {
    $p = Join-Path $sandbox 'nosrc.cfg'
    Copy-Item -LiteralPath $srcCfgPath -Destination $p
    [IO.File]::WriteAllLines($p, (@(Get-Content -LiteralPath $p) -replace '^seta r_renderResolution "[^"]*"$', 'seta r_renderResolution "0.5184"'))
    [void]$engine.Execute("hmwApplyWindowedMode(" + (ConvertTo-Json $p) + ", " + (ConvertTo-Json (Join-Path $sandbox 'absent.cfg')) + ");")
    (Get-Content -LiteralPath $p | Where-Object { $_ -like 'seta r_renderResolution *' }) -eq 'seta r_renderResolution "0.5184"'
}
Check 'windowed pass is idempotent'              {
    $before = (Get-FileHash $aPath).Hash
    [void]$engine.Execute("hmwApplyWindowedMode(" + (ConvertTo-Json $aPath) + ", " + (ConvertTo-Json $srcCfgPath) + ");")
    (Get-FileHash $aPath).Hash -eq $before
}

# An instance set up by the version that crashed still has the off-screen
# position on disk. The handler has to actively undo it, not merely stop writing
# it, or the crash reproduces on the next launch.
$stalePath = Join-Path $sandbox 'stale.cfg'
@(
    'seta r_fullscreen "1"',
    'seta r_fullscreenWindow "1"',
    'seta r_mode "2560x1440"',
    'seta r_aspectRatio "auto"',
    'seta r_renderResolutionNative "0"',
    'seta vid_xpos "0"',
    'seta vid_ypos "720"'
) -join "`r`n" | Set-Content -LiteralPath $stalePath -Encoding Ascii -NoNewline
[void]$engine.Execute("hmwApplyWindowedMode(" + (ConvertTo-Json $stalePath) + ", " + (ConvertTo-Json $srcCfgPath) + ");")
$staleCfg = Get-Content -LiteralPath $stalePath
Check 'stale off-screen vid_ypos is undone'      {
    (@($staleCfg | Where-Object { $_ -eq 'seta vid_ypos "-1"' }).Count -eq 1) -and
    (@($staleCfg | Where-Object { $_ -eq 'seta vid_ypos "720"' }).Count -eq 0)
}
Check 'stale fullscreen flags are undone'        {
    (@($staleCfg | Where-Object { $_ -eq 'seta r_fullscreen "0"' }).Count -eq 1) -and
    (@($staleCfg | Where-Object { $_ -eq 'seta r_fullscreenWindow "0"' }).Count -eq 1)
}

# HMW_SHOW_FPS = false must leave the player's own in-game choice untouched.
$optOutPath = Join-Path $sandbox 'nofps.cfg'
'seta cg_infobar_fps "0"' | Set-Content -LiteralPath $optOutPath -Encoding Ascii -NoNewline
[void]$engine.Execute("HMW_SHOW_FPS = false; var offOk = hmwApplyFpsCounter(" + (ConvertTo-Json $optOutPath) + ");")
Check 'HMW_SHOW_FPS false reports skipped'       { $engine.GetValue('offOk').ToObject() -eq $false }
Check 'HMW_SHOW_FPS false writes nothing'        {
    (Get-Content -LiteralPath $optOutPath -Raw).Trim() -eq 'seta cg_infobar_fps "0"'
}
[void]$engine.Execute('HMW_SHOW_FPS = true;')

# --- graphics presets --------------------------------------------------------
$presetDir = Join-Path $sandbox 'Graphics'
New-Item -ItemType Directory -Path $presetDir -Force | Out-Null
@(
    '// a comment',
    '# another comment',
    '',
    '   ',
    'seta r_picmip "3"',
    'seta sm_enable "0"',
    'r_texFilterAnisoMax "1"',              # bare form, no seta
    'seta sm_tileResolution "High"',        # string value
    'seta r_fullscreen "1"',               # blocked, would break split-screen
    'seta vid_ypos "720"',                 # blocked, this exact value crashed an instance
    'seta name "hacker"',                  # blocked, would collapse profiles
    'total garbage line with no value'     # tolerated, must not throw
) | Set-Content -LiteralPath (Join-Path $presetDir 'Low.cfg') -Encoding Ascii

$instCfg = Join-Path $p2 'config_mp.cfg'

function ApplyPreset([string]$preset, [string]$cfg, [string]$srcCfg = (Join-Path $srcP2 'config_mp.cfg')) {
    $js = "var applied = hmwApplyGraphicsPreset(" + (ConvertTo-Json $cfg) + ", " +
          (ConvertTo-Json $preset) + ", " + (ConvertTo-Json $presetDir) + ", " +
          (ConvertTo-Json $srcCfg) + ");"
    [void]$engine.Execute($js)
    return [int]$engine.GetValue('applied').ToObject()
}
function PresetCfg([string]$cfg, [string]$key) {
    @(Get-Content -LiteralPath $cfg | Where-Object { $_ -like "$key *" })
}

# "Default" must undo a preset, not sit there doing nothing. When it was a no-op,
# selecting Low once left r_picmip "3" and sm_enable "0" in that instance's config
# permanently, and a real instance was still carrying them long after the dropdown
# had been put back to Default. It crashed 6 s into startup.
$defCfg = Join-Path $sandbox 'preset-default.cfg'
Copy-Item -LiteralPath $instCfg -Destination $defCfg -Force
# Something the user changed in-game that no preset manages: must survive.
[void]$engine.Execute("hmwSetCfgValue(" + (ConvertTo-Json $defCfg) + ", 'seta cg_fov', '80');")
[void](ApplyPreset 'Low' $defCfg)
Check 'drifted first, so the revert is not vacuous' {
    ((PresetCfg $defCfg 'seta r_picmip') -contains 'seta r_picmip "3"') -and
    ((PresetCfg $defCfg 'seta sm_enable') -eq 'seta sm_enable "0"') -and
    ((PresetCfg $defCfg 'seta r_texFilterAnisoMax') -eq 'seta r_texFilterAnisoMax "1"')
}
$defCount = ApplyPreset 'Default' $defCfg
Check 'Default reverted the drifted dvars'       {
    ((PresetCfg $defCfg 'seta r_picmip') -contains 'seta r_picmip "0"') -and
    ((PresetCfg $defCfg 'seta sm_enable') -eq 'seta sm_enable "1"') -and
    ((PresetCfg $defCfg 'seta r_texFilterAnisoMax') -eq 'seta r_texFilterAnisoMax "4"')
}
Check 'Default reported what it restored'        { $defCount -ge 3 }
Check 'Default left an unmanaged dvar alone'     { (PresetCfg $defCfg 'seta cg_fov') -eq 'seta cg_fov "80"' }
Check 'Default did not resurrect blocked dvars'  {
    ((PresetCfg $defCfg 'seta name') -eq 'seta name "Player2"') -and
    ((PresetCfg $defCfg 'seta vid_ypos') -eq 'seta vid_ypos "-1"') -and
    ((PresetCfg $defCfg 'seta r_fullscreen') -eq 'seta r_fullscreen "0"')
}
# A missing install config must not wipe anything.
$noSrcCfg = Join-Path $sandbox 'preset-nosrc.cfg'
Copy-Item -LiteralPath $instCfg -Destination $noSrcCfg -Force
$noSrcBefore = Get-Content -LiteralPath $noSrcCfg -Raw
$noSrcCount = ApplyPreset 'Default' $noSrcCfg (Join-Path $sandbox 'does-not-exist.cfg')
Check 'Default with no install config is a no-op' {
    ($noSrcCount -eq 0) -and ((Get-Content -LiteralPath $noSrcCfg -Raw) -eq $noSrcBefore)
}

# An unknown or missing preset must also change nothing rather than throw.
$missCfg = Join-Path $sandbox 'preset-missing.cfg'
Copy-Item -LiteralPath $instCfg -Destination $missCfg -Force
$missBefore = Get-Content -LiteralPath $missCfg -Raw
$missCount = ApplyPreset 'Nonexistent' $missCfg
Check 'missing preset file applies nothing'      { $missCount -eq 0 }
Check 'missing preset file changes no bytes'     { (Get-Content -LiteralPath $missCfg -Raw) -eq $missBefore }
Check 'missing preset file is logged'            {
    (Get-Content -LiteralPath $logPath -Raw) -match "graphics preset 'Nonexistent' has no file"
}

# The real thing, over a config that already went through the windowed pass.
$lowCfg = Join-Path $sandbox 'preset-low.cfg'
Copy-Item -LiteralPath $instCfg -Destination $lowCfg -Force
$lowCount = ApplyPreset 'Low' $lowCfg
Check 'Low preset applied 4 allowed dvars'       { $lowCount -eq 4 }
Check 'preset set r_picmip'                      { (PresetCfg $lowCfg 'seta r_picmip') -contains 'seta r_picmip "3"' }
Check 'preset set sm_enable'                     { (PresetCfg $lowCfg 'seta sm_enable') -eq 'seta sm_enable "0"' }
Check 'preset honoured the bare no-seta form'    { (PresetCfg $lowCfg 'seta r_texFilterAnisoMax') -eq 'seta r_texFilterAnisoMax "1"' }
Check 'preset kept a string value intact'        { (PresetCfg $lowCfg 'seta sm_tileResolution') -eq 'seta sm_tileResolution "High"' }
# A looser regex once parsed the prose line as a dvar named "total" and wrote it
# straight into config_mp.cfg.
Check 'prose line did not become a dvar'         { (PresetCfg $lowCfg 'seta total').Count -eq 0 }
Check 'unparseable line counted in the log'      {
    (Get-Content -LiteralPath $logPath -Raw) -match 'skipped 1 unparseable line'
}

# The blocklist is the guard that stops an edited preset undoing the two fixes
# that took a crash each to find.
Check 'blocked r_fullscreen stayed off'          { (PresetCfg $lowCfg 'seta r_fullscreen') -eq 'seta r_fullscreen "0"' }
Check 'blocked vid_ypos stayed at -1'            { (PresetCfg $lowCfg 'seta vid_ypos') -eq 'seta vid_ypos "-1"' }
Check 'blocked name untouched'                   { (PresetCfg $lowCfg 'seta name') -eq 'seta name "Player2"' }
# Non-vacuity: with the blocklist emptied the same preset file must actually
# break windowing, otherwise the three checks above prove nothing.
Check 'blocklist is what stops r_fullscreen'     {
    $unguarded = Join-Path $sandbox 'preset-unguarded.cfg'
    Copy-Item -LiteralPath $instCfg -Destination $unguarded -Force
    [void]$engine.Execute('var savedBlocked = HMW_PRESET_BLOCKED; HMW_PRESET_BLOCKED = [];')
    [void](ApplyPreset 'Low' $unguarded)
    [void]$engine.Execute('HMW_PRESET_BLOCKED = savedBlocked;')
    ((PresetCfg $unguarded 'seta r_fullscreen') -eq 'seta r_fullscreen "1"') -and
    ((PresetCfg $unguarded 'seta vid_ypos') -eq 'seta vid_ypos "720"') -and
    ((PresetCfg $unguarded 'seta name') -eq 'seta name "hacker"')
}
Check 'blocklist restored after that check'      {
    [void]$engine.Execute('var blockedCount = HMW_PRESET_BLOCKED.length;')
    [int]$engine.GetValue('blockedCount').ToObject() -eq 7
}
Check 'blocked dvars are logged'                 {
    (Get-Content -LiteralPath $logPath -Raw) -match 'ignored r_fullscreen, vid_ypos, name'
}
# r_picmip is a prefix of r_picmip_bump, and the preset only names the short one.
Check 'preset did not create r_picmip_bump'      { (PresetCfg $lowCfg 'seta r_picmip_bump').Count -eq 0 }
Check 'preset duplicated no dvar'                {
    $keys = Get-Content -LiteralPath $lowCfg | Where-Object { $_ -match '^seta (\S+)' } |
            ForEach-Object { ($_ -split ' ')[1] }
    ($keys | Group-Object | Where-Object Count -gt 1).Count -eq 0
}
Check 'preset is idempotent'                     {
    $once = Get-Content -LiteralPath $lowCfg -Raw
    [void](ApplyPreset 'Low' $lowCfg)
    (Get-Content -LiteralPath $lowCfg -Raw) -eq $once
}

# --- frame cap ---------------------------------------------------------------
# HMW_FRAME_CAPS itself lives below the Game definition marker, so the allowed
# list is injected here and asserted against the source file further down.
$caps = @('60', '90', '144', '240')
$capsJs = ConvertTo-Json $caps
function ApplyCap([string]$cfg, $selection) {
    $js = "var chosen = hmwApplyFrameCap(" + (ConvertTo-Json $cfg) + ", " +
          (ConvertTo-Json $selection) + ", " + $capsJs + ");"
    [void]$engine.Execute($js)
    return [string]$engine.GetValue('chosen').ToObject()
}

$capCfg = Join-Path $sandbox 'framecap.cfg'
'seta com_maxfps "0"' | Set-Content -LiteralPath $capCfg -Encoding Ascii
Check 'cap 144 is written'                       {
    (ApplyCap $capCfg '144') -eq '144' -and
    ((PresetCfg $capCfg 'seta com_maxfps') -eq 'seta com_maxfps "144"')
}
Check 'uncapped install value is replaced'       { (PresetCfg $capCfg 'seta com_maxfps').Count -eq 1 }
Check 'cap is idempotent'                        {
    $once = Get-Content -LiteralPath $capCfg -Raw
    [void](ApplyCap $capCfg '144')
    (Get-Content -LiteralPath $capCfg -Raw) -eq $once
}
Check 'every offered cap is accepted'            {
    $ok = $true
    foreach ($c in $caps) {
        if ((ApplyCap $capCfg $c) -ne $c) { $ok = $false }
        if ((PresetCfg $capCfg 'seta com_maxfps') -ne "seta com_maxfps `"$c`"") { $ok = $false }
    }
    $ok
}
# A junk selection must never reach config_mp.cfg. com_maxfps "abc" would be the
# game's problem to interpret, and a nonsense cap looks exactly like a GPU that
# cannot keep up, which is the hardest kind of bug to attribute.
foreach ($bad in @('abc', '', '0', '61', '144 ')) {
    $label = if ($bad -eq '') { '(empty)' } else { "'$bad'" }
    Check "junk cap $label falls back to 60"     {
        ((ApplyCap $capCfg $bad) -eq '60') -and
        ((PresetCfg $capCfg 'seta com_maxfps') -eq 'seta com_maxfps "60"')
    }
}
Check 'fallback is logged, not silent'           {
    (Get-Content -LiteralPath $logPath -Raw) -match "frame cap: no valid selection \('abc'\), falling back to 60 fps"
}
# Falling back rather than skipping matters: skipping would leave com_maxfps "0",
# and uncapped is the exact setting the dropdown exists to prevent.
Check 'junk never leaves the cap uncapped'       {
    'seta com_maxfps "0"' | Set-Content -LiteralPath $capCfg -Encoding Ascii
    [void](ApplyCap $capCfg 'nonsense')
    (PresetCfg $capCfg 'seta com_maxfps') -ne 'seta com_maxfps "0"'
}
# com_maxfps is on the blocklist, so a hand-edited preset cannot quietly outrank
# the dropdown.
Check 'a preset cannot override the cap'         {
    $capPresetDir = Join-Path $sandbox 'GraphicsCap'
    New-Item -ItemType Directory -Path $capPresetDir -Force | Out-Null
    'seta com_maxfps "500"' | Set-Content -LiteralPath (Join-Path $capPresetDir 'Low.cfg') -Encoding Ascii
    $fightCfg = Join-Path $sandbox 'framecap-fight.cfg'
    'seta com_maxfps "0"' | Set-Content -LiteralPath $fightCfg -Encoding Ascii
    $js = "hmwApplyGraphicsPreset(" + (ConvertTo-Json $fightCfg) + ", 'Low', " +
          (ConvertTo-Json $capPresetDir) + ", " + (ConvertTo-Json (Join-Path $srcP2 'config_mp.cfg')) + ");"
    [void]$engine.Execute($js)
    [void](ApplyCap $fightCfg '90')
    (PresetCfg $fightCfg 'seta com_maxfps') -eq 'seta com_maxfps "90"'
}

# Every shipped preset must parse, apply cleanly, and never trip the blocklist.
$shippedDir = Join-Path (Split-Path -Parent $PSScriptRoot) 'HorizonMW\Graphics'
foreach ($name in @('Minimum', 'Low', 'Medium', 'High', 'Extra')) {
    $shipCfg = Join-Path $sandbox "shipped-$name.cfg"
    Copy-Item -LiteralPath $instCfg -Destination $shipCfg -Force
    $js = "var n = hmwApplyGraphicsPreset(" + (ConvertTo-Json $shipCfg) + ", " +
          (ConvertTo-Json $name) + ", " + (ConvertTo-Json $shippedDir) + ");"
    [void]$engine.Execute($js)
    $n = [int]$engine.GetValue('n').ToObject()
    Check "shipped $name applies dvars"          { $n -ge 8 }
    Check "shipped $name keeps windowing intact" {
        ((PresetCfg $shipCfg 'seta r_fullscreen') -eq 'seta r_fullscreen "0"') -and
        ((PresetCfg $shipCfg 'seta vid_ypos') -eq 'seta vid_ypos "-1"') -and
        ((PresetCfg $shipCfg 'seta name') -eq 'seta name "Player2"')
    }
    Check "shipped $name duplicates nothing"     {
        $keys = Get-Content -LiteralPath $shipCfg | Where-Object { $_ -match '^seta (\S+)' } |
                ForEach-Object { ($_ -split ' ')[1] }
        ($keys | Group-Object | Where-Object Count -gt 1).Count -eq 0
    }
}
Check 'dropdown names all have a preset file'    {
    $declared = ([regex]::Match($src,
        'HMW_GRAPHICS_PRESETS\s*=\s*\[(.*?)\]').Groups[1].Value -split ',') |
        ForEach-Object { $_.Trim().Trim('"') } | Where-Object { $_ -and $_ -ne 'Default' }
    $missing = $declared | Where-Object { -not (Test-Path (Join-Path $shippedDir "$_.cfg")) }
    (@($declared).Count -eq 5) -and (@($missing).Count -eq 0)
}

# The dropdown wiring lives below the Game definition marker, where the Jint
# prelude cannot reach it, so assert it against the source text.
Check 'frame cap dropdown offers 60/90/144/240' {
    $declared = ([regex]::Match($src,
        'HMW_FRAME_CAPS\s*=\s*\[(.*?)\]').Groups[1].Value -split ',') |
        ForEach-Object { $_.Trim().Trim('"') } | Where-Object { $_ }
    (Compare-Object $declared @('60', '90', '144', '240') -SyncWindow 0) -eq $null
}
Check 'frame cap is bound to the FrameCap key'   {
    # [^;]*? rather than [^)]*: the option label contains "(fps)", so a
    # paren-excluding pattern never reaches the key and the check passed vacuously.
    $src -match '(?s)Game\.AddOption\([^;]*?"FrameCap",\s*HMW_FRAME_CAPS'
}
# Ordering is load-bearing: a preset applied afterwards could overwrite the cap.
# Compared inside Play only, because both functions are *defined* earlier in the
# file and in the opposite order, so a whole-file IndexOf compares declarations
# rather than call sites and always fails.
Check 'cap is applied after the graphics preset' {
    $playBody = $src.Substring($src.IndexOf('Game.Play = function'))
    $presetCall = $playBody.IndexOf('hmwApplyGraphicsPreset' + '(')
    $capCall    = $playBody.IndexOf('hmwApplyFrameCap' + '(')
    ($presetCall -ge 0) -and ($capCall -gt $presetCall)
}
Check 'com_maxfps is reserved from presets'      {
    ([regex]::Match($src, 'HMW_PRESET_BLOCKED\s*=\s*\[(.*?)\]',
        'Singleline').Groups[1].Value) -match '"com_maxfps"'
}

Check 'hwgd.pf is exactly 39 bytes'             { (Get-Item -LiteralPath (Join-Path $p2 'hwgd.pf')).Length -eq 39 }
Check 'hwgd.pf ends with a single 0x00'         {
    $b = [IO.File]::ReadAllBytes((Join-Path $p2 'hwgd.pf'))
    $b[38] -eq 0 -and $b[37] -eq [byte][char]'}'
}
Check 'hwgd.pf has no BOM'                      { ([IO.File]::ReadAllBytes((Join-Path $p2 'hwgd.pf')))[0] -eq [byte][char]'{' }
Check 'hwgd.pf backed up before overwrite'      { (Get-Content -LiteralPath (Join-Path $sandbox 'appdata\hwgd.pf.nucleus-original') -Raw) -eq 'REAL-GUID' }
Check 'hmw-key backed up before deletion'       { (Get-Content -LiteralPath (Join-Path $sandbox 'appdata\hmw-key.nucleus-original') -Raw) -eq 'REAL-KEY' }
Check 'no backup made for absent hmw-key.pub'   { -not (Test-Path (Join-Path $sandbox 'appdata\hmw-key.pub.nucleus-original')) }
Check 'guest identity was actually mutated'     {
    (Get-Item -LiteralPath (Join-Path $sandbox 'appdata\hwgd.pf')).Length -eq 39 -and
    -not (Test-Path (Join-Path $sandbox 'appdata\hmw-key'))
}

# restore, then assert the original identity is byte-identical again
[void]$engine.Execute('hmwRestoreIdentity();')
Check 'restore brings hwgd.pf back'             { (Get-Content -LiteralPath (Join-Path $sandbox 'appdata\hwgd.pf') -Raw) -eq 'REAL-GUID' }
Check 'restore brings hmw-key back'             { (Get-Content -LiteralPath (Join-Path $sandbox 'appdata\hmw-key') -Raw) -eq 'REAL-KEY' }
Check 'backups removed after restore'           { -not (Test-Path (Join-Path $sandbox 'appdata\hwgd.pf.nucleus-original')) }
[void]$engine.Execute('hmwRestoreIdentity();')
Check 'second restore is a no-op'               { (Get-Content -LiteralPath (Join-Path $sandbox 'appdata\hwgd.pf') -Raw) -eq 'REAL-GUID' }

Remove-Item -LiteralPath $sandbox -Recurse -Force -ErrorAction SilentlyContinue

if ($fail -gt 0) { "$fail check(s) failed"; exit 1 } else { 'all checks passed'; exit 0 }
